language: csharp
mono:
- 3.12.0
sudo: required
before_script:
- sudo apt-get install build-essential
- sudo apt-get install python libssl-dev curl
- curl https://raw.github.com/creationix/nvm/master/install.sh | sh
- nvm install 0.12
script:
- ". ./travis-build.sh"
deploy:
  provider: npm
  email: david.driscoll@gmail.com
  api_key:
    secure: gC928QE/c38zu2zEZMuUpMc7hYZo0cLgvEpjoKnw+dY5VPlhhtbtykME58OfRYhkax2CFlZvqtbEMo8vb0CR1tWlGAtiMJz8t771Jdg8BBPqG8n1nz/KO2+ZoZSDdfSppdp8d2xhPzkHV/ug1V6WQNukEucfKFxscpRfkUG0RIE=
  on:
    tags: true
    repo: OmniSharp/omnisharp-server-roslyn-binaries
after_deploy:
- cat npm-debug.log
